# =============================================================================
# =============================================================================

- name: display message
  debug:
    msg:
      - 'This playbook is for libvirt tasks, started at {{ansible_date_time.iso8601}}:'

- name:  main block
  block:

    - include_tasks:   libvirt_shared_storage.yml

  become:               yes
  become_user:          root
