# =============================================================================
# Install Oracle GI 19.3.0 Software Only:
# =============================================================================

- name: Ansible check directory.
  shell: >
     stat {{ item }}
  with_items:
    - "{{ gv_guest_staging_dir }}"
    - "{{ gv_inventory_loc }}"
    - "{{ gv_grid_base }}"
  register: u01_stat
  tags:
   - never

- debug: msg="{{item.stdout}}"
  with_items: "{{ u01_stat.results }}"
  tags:
   - never

- name: create required directories
  become: yes
  remote_user: "{{ gv_root_user }}"
  become: yes
  become_method: sudo
  become_user: "{{ gv_root_user }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gv_grid_user }}"
    group: "{{ gv_oracle_install_group }}"
    recurse: yes
    mode: 0775
  with_items:
    - "{{ gv_guest_staging_dir }}"
    - "{{ gv_inventory_loc }}"
    - "{{ gv_grid_base }}"
