# =============================================================================
# Install Oracle GI 19.3.0 Software Only:
# (1) Assumption: Oracle GI software is downloaded and staged
# (2) Install cluster verification utility
# (3) Unpack Oracle GI software to the Oracle Home directory into the first node
# (4) Run cluster Verification Checks for CRS Installation
# =============================================================================

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False
  tags:
    - oracle_sys_config

