# =============================================================================

- name: Enable powertools
  ansible.builtin.shell: dnf config-manager --set-enabled powertools

- name: Install the latest version of packages
  dnf:
    name:
      - libvirt-devel
      - libvirt-libs
      - epel-release
      - device-mapper-multipath
      - smartmontools
      - avahi
      - chrony
      - net-tools
    state: latest

- name: Install rlwrap
  ansible.builtin.shell: dnf install -y rlwrap

- name: enable multipath
  ansible.builtin.shell: mpathconf --enable --with_multipathd y
