# =============================================================================
# =============================================================================

- import_tasks: variables.yml

- name: display message
  debug:
    msg:
      - 'This oracle-sys-config-role role , started at {{ansible_date_time.iso8601}}:'

- name: 
  block:
    - import_tasks:     disable_selinux.yml
    - import_tasks:     disable_firewall.yml
    - import_tasks:     import_packages.yml
    - import_tasks:     set_pam_limits.sh
    - import_tasks:     install_oracle_prerequisites.yml
    - import_tasks:     create_u01_filesystem.yml
    - import_tasks:     add_oracle_groups.yml
    - import_tasks:     add_grid_user.yml
    - import_tasks:     configuse_tmpfs.yml
    - import_tasks:     create_required_dirs.yml
  become:               yes
  become_user:          root
