# =============================================================================
# =============================================================================

- name: configure hostname and domain name
  net_system:
    hostname: "{{ host_name }} "
    domain_name: "{{ domain_name }} "
    domain-search:
      - "{{ domain_name }} "
  tags:
    - oracle_sys_config
    - set_hostname_domain_name

