- hosts: "{{ hostgroup | default('rac19c01') }}"
  user: root
  vars:
    swap_file_size_mb: '8192'
  tasks:

    - set_fact: home="{{ lookup('env','ANSIBLE_HOME') }}"

    - name: Include vars of var/common
      include_vars:
        dir: "{{ home }}/vars/common"
      tags:
        - always

    ########################################
    #- meta: end_play
    ########################################

    - name: pre gridSetup.sh block 
      block:

    ########################################
    # resize disable ipv6
    ########################################

        ########################################
        # resize vm root disk
        ########################################
    
        - include_role:
            name: libvirt-shared-storage-role
            tasks_from: "{{ item }}"
          loop:
            - install-custom-facts
            - resize_domains_disk_image

        - name: Waiting for resurection
          wait_for_connection:
          delay: 60
          timeout: 300
    
        ########################################
        # configure eth1/eth2
        ########################################

        - name: Install the latest version of net-tools
          dnf:
             name: net-tools
             state: latest
    
        # install custom facts

        - include_role:
            name: ansible-misc-role
            tasks_from: "{{ item }}"
          loop:
            - install-custom-facts
    
        - include_role:
             name: ansible-network-role
          vars:
            network_ifaces:
              - device: eth1
                ip: "{{ ansible_facts['ansible_local']['nic']['eth1']['ipaddr'] }}"
                netmask: "{{ ansible_facts['ansible_local']['nic']['eth1']['netmask'] }}"
                type: ethernet
              - device: eth2
                ip: "{{ ansible_facts['ansible_local']['nic']['eth2']['ipaddr'] }}"
                netmask: "{{ ansible_facts['ansible_local']['nic']['eth2']['netmask'] }}"
                type: ethernet
    
        ########################################
        # set swap size
        ########################################
    
        - name: Wait 600 seconds for target connection to become reachable/usable
          wait_for_connection:
            delay: 60
            timeout: 120
    
        - include_role:
            name: system-swap-role
    
        - include_role:
            name: oracle-sys-config-role
    
        ########################################
        # create libvirt shared disks for ASM
        ########################################
        - include_role:
            name: libvirt-shared-storage-role
    
        ########################################
        # oracle-mpath-role - configure udev/mpath
        ########################################
    
        - name: set facts to override oracle-mpath-role role defaults
          set_fact:
            device_persistence: "{{ gv_device_persistence }}"
            asm_diskgroups: "{{ gv_asm_diskgroups }}"
            oracle_stage: "{{ gv_guest_staging_dir }}"
            oracle_rsp_stage: "{{ gv_guest_staging_dir }}"
            grid_install_user: "{{ gv_grid_user }}"
            use_partition_devices: "{{ gv_use_partition_devices }}"
            partition_devices: false
            configure_cluster: true
    
        - include_role:
            name: oracle-mpath-role
          vars:
            become: yes
            remote_user: "{{ gv_root_user }}"
            become_user: "{{ gv_root_user }}"
    
        ########################################
        # oracle-inventory-role
        ########################################
    
        - name: set facts to override oracle-inventory role defaults
          set_fact:
            inventory_directory: "{{ gv_inventory_loc }}"
            inventory_owner: "{{ gv_grid_user }}"
            install_group: "{{ gv_oracle_install_group }}"
    
        - include_role:
            name: oracle-inventory-role
          vars:
            become: yes
            remote_user: "{{ gv_root_user }}"
            become_user: "{{ gv_root_user }}"
    
        ########################################
        # 
        ########################################

        - include_role:
             name: ansible-ipv6-role
    
        - name: Unconditionally reboot the machine with all defaults
          reboot:

      when: pre_grid_setup is defined

      #################################
      # end of block 
      #################################

    - include_role:
        name: oracle-gi-install-role
      tags:
        - always
        - oracle-gi-install
