- name: with_indexed_items -> loop
  ansible.builtin.debug:
    msg: "{{ hostvars[ip_item]['node_public_ip'] }} {{ hostvars[ip_item]['node_fq_host_name'] }} {{ hostvars[ip_item]['node_host_name'] }}"
  loop: "{{ gv_gi_server_list|flatten(levels=1) }}"
  loop_control:
    index_var: index
    loop_var: ip_item

- meta: end_play

- name: amend hosts file with public, private and virtual ips.
  remote_user: "{{ gv_root_user }}"
  blockinfile:
    path: /etc/hosts2
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{ ip_item }} -->"
    block: |
       # public
       {{ hostvars[ip_item]['node_public_ip'] }} {{ hostvars[ip_item]['node_fq_host_name'] }} {{ hostvars[ip_item]['node_host_name'] }} 
       # private
       {{ hostvars[ip_item]['node_priv_ip'] }} {{ hostvars[ip_item]['node_priv_name'] }}
       # virtual
       {{ hostvars[ip_item]['node_vip_ip'] }} {{ hostvars[ip_item]['node_fq_vip_name'] }} {{ hostvars[ip_item]['node_vip_name'] }}
       # scan
  loop:
     - "{{ gv_gi_server_list|flatten(levels=1) }}"
  loop_control:
     loop_var: ip_item
     index_var: index

- name: amend hosts file with public, private and virtual ips.
  remote_user: "{{ gv_root_user }}"
  blockinfile:
    path: /etc/hosts2
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK SCAN  -->"
    block: |
       {{ hostvars[ip_item]['gv_oracle_scan_ip_1'] }} {{ hostvars[ip_item]['gv_oracle_fq_scan_name'] }} {{ hostvars[ip_item]['gv_oracle_scan_name'] }}
       {{ hostvars[ip_item]['gv_oracle_scan_ip_2'] }} {{ hostvars[ip_item]['gv_oracle_fq_scan_name'] }} {{ hostvars[ip_item]['gv_oracle_scan_name'] }}
       {{ hostvars[ip_item]['gv_oracle_scan_ip_3'] }} {{ hostvars[ip_item]['gv_oracle_fq_scan_name'] }} {{ hostvars[ip_item]['gv_oracle_scan_name'] }}
  with_items:
     - "{{ gv_gi_server_list|flatten(levels=1) }}"
  loop_control:
    index_var: index
    loop_var: ip_item
